### PR TITLE
fix(lib): fix related errors of ratio calculation

### LINKED ISSUE #9: [Bug] Duplication rate is the inverse one (non-similar rate) not expected

### PR DESCRIPTION
**Pull request by PeterWang-dev**
1. Fixed wrong duplication rate;
2. Fixed wired function in unittest;
3. Fixed error in integration test.

Fixes #9

### CODE REVIEW

File: src/processor.rs [hunk 1]
```diff
@@ -1,3 +1,5 @@
+use std::result;
+
 use textdistance::nstr::damerau_levenshtein;
```
Comment (PeterWang-dev) [inline src/processor.rs:3]: Remove unnecessary modules.

```suggestion
use textdistance::nstr::damerau_levenshtein;
```
